site_name: Wimsey

nav:
  - Intro: index.md
  - Quick Start: quick-start.md
  - Building Tests: building-tests.md
  - Motivation: motivation.md
  - Test Catalogue: possible-tests.md

theme:
  name: material
  icon:
    logo: fontawesome/solid/magnifying-glass-chart
  palette:
    - scheme: default
      primary: brown
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: brown
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-night
        name: Switch to light mode
repo_name: benrutter/wimsey
repo_url: https://github.com/benrutter/wimsey

plugins:
  - search
  - charts

extra_javascript:
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
  - pymdownx.tabbed:
      alternate_style: true
